services:

  front:
    build: ./front
    volumes:
      - './front:/app'
    ports:
      - '5173:5173'

  crud:
    build: ./crud
    volumes:
      - './crud:/go/src/app'
    ports:
      - '8080:8080'

  mid:
    build: ./mid
    volumes:
      - './mid:/app'
    ports:
      - '3000:3000'
