services:

  front:
    build: ./front

  crud:
    build: ./crud
    volumes:
      - './crud:/go/src/app'
    ports:
      - '8080:8080'

  mid:
    build: ./mid
    volumes:
      - './mid:/app'
    ports:
      - '8079:3000'
