# Target: Use golang as base for CRUD API
# Some of the following frameworks:
# https://www.moesif.com/blog/api-product-management/api-analytics/Top-5-GO-REST-API-Frameworks/
# https://nordicapis.com/7-frameworks-to-build-a-rest-api-in-go/
FROM golang:1.21
